name: safesign_off
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  google_maps_flutter: ^2.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  
flutter:
  assets:
    - assets/images/
    - assets/icons/

